name: livenight_skyview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.2.0
  geolocator: ^14.0.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
