name: livenight_skyview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^10.2.0
  geolocator: ^14.0.2
  http: ^0.13.4
  flutter_compass: ^0.8.1
  provider: ^6.1.5+1
  flutter_gl: ^0.0.21
  three_dart_jsm: ^0.0.10
  three_dart: ^0.0.16
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1

flutter:
  assets:
    - lib/assets/images/